<?php
/**
 * @file
 * Defines composed field types.
 */

/**
 * Implements hook_field_info().
 */
function composed_field_field_info() {
  return array(
    // We name our field as the associative name of the array.
    'composed_field' => array(
      'label' => t('Composed field'),
      'description' => t('This field stores serialized array in the database.'),
      'default_widget' => 'composed_field_widget',
      'default_formatter' => 'composed_field_formatter',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function composed_field_field_widget_info() {
  return array(
    'composed_field_widget' => array(
      'label' => t('Composed field'),
      'field types' => array('composed_field'),
      // 'settings' => array('rows' => 5),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function composed_field_field_formatter_info() {
  return array(
    // This formatter just displays the hex value in the color indicated.
    'composed_field_formatter' => array(
      'label' => t('Composed field'),
      'field types' => array('composed_field'),
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
function composed_field_field_is_empty($item, $field) {
  //return empty($item['rgb']);
  
  // TODO:
  return FALSE;
  
}

/**
 * Implements hook_field_widget_settings_form().
 */
function composed_field_field_widget_settings_form($field, $instance) {
  // Array of previously saved setting values.
  $default_values = $instance['widget']['settings'];
  $number_of_subfields_title = t('Number of subfields');

  $default_values['number_of_subfields'] = 3;

  if (empty($default_values['number_of_subfields'])) {
    $default_values['number_of_subfields'] = '';
    $number_of_subfields = 1;
    // State of the Widget Form elements.
    $disabled = TRUE;
    // Single default value.
    $default_value = t('You must enter a value into !number_of_subfields', array('!number_of_subfields' => $number_of_subfields_title));
  }
  else {
    $number_of_subfields = $default_values['number_of_subfields'];
    // State of the Widget Form elements.
    $disabled = FALSE;
    // Single default value.
    $default_value = '';
  }

  $form['inline'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display as inline element'),
    '#default_value' => (empty($default_values['inline'])) ? FALSE : $default_values['inline'],
  );

  // This element determines how many subfields our field will have.
  $form['number_of_subfields'] = array(
    '#type' => 'textfield',
    '#title' => $number_of_subfields_title,
    '#description' => t('Enter a numeric value and hit the tab key after that.') . '<br />' .
      t('This value determines how many subfields this field will have.'),
    '#default_value' => $default_values['number_of_subfields'],
    '#maxlength' => 2,
    '#size' => 2,
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
    '#ajax' => array(
      'callback' => '_composed_field_number_of_fields_ajax_callback',
    ),
  );

  $form['composed_field'] = array(
    '#type' => 'vertical_tabs',
  );

  $form_controls = _composed_field_form_controls_api();

  foreach($form_controls as $form_control => $form_control_values) {
    // The Form API wont allow form element names starting with #, so we add a _
    // before the form control attribute name.
    $form_control_attribute = "_$form_control";

    // Set a vertical tab for each form control attribute.
    $form['composed_field'][$form_control_attribute] = array(
      '#title' => $form_control,
      '#type' => 'fieldset',
      '#description' => t('See !form_controls for more details.',
        array('!form_controls' => l(t('Form Controls'),
        'http://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7',
        array('attributes' => array('target' => '_blank'))))
      ),
    );
    

    
    // Build the widget form in each tab.
    for ($subfield = 1;
         $subfield <= $number_of_subfields;
         $subfield++) {


      foreach($form_control_values['widget_form'] as $form_element => $form_element_properties) {



        $form_element_properties['#disabled'] = $disabled;

        if ($form_control == '#type') {
          if ($disabled) {
            // The user hasn't entered a value into Number of subfields as yet.
            $form_element_properties['#options'] = array('' => $default_value);
          }
        }
        else {
          // Some form control attributes are not required depending on the
          // form control type selected on each subfield.
          $form['composed_field'][$form_control_attribute][$subfield]['enabled'] = array(
            '#type' => 'checkbox',
            '#title' => t('Enable !attribute attribute for Subfield !subfield.', array('!attribute' => $form_control, '!subfield' => $subfield)),
            '#disabled' => $disabled,
            '#ajax' => array(
              'callback' => '_composed_field_enabled_ajax_callback',
            ),
          );
        }


        // Set default value for $instance['widget']['settings'].
        $form_element_properties['#default_value'] = $default_value;
        if (!empty($default_values['composed_field'][$form_control_attribute][$subfield][$form_element])) {
          $form_element_properties['#default_value'] = $default_value = $default_values['composed_field'][$form_control_attribute][$subfield][$form_element];
        }

        // Check if this is the element that holds the form control property
        // value.
        if ($form_element == 'value') {
          // Set title.
          $title = (empty($form_element_properties['#title'])) ? '' : $form_element_properties['#title'];
          $form_element_properties['#title'] = $title . t('Subfield !subfield', array('!subfield' => $subfield));
        }
        $form['composed_field'][$form_control_attribute][$subfield][$form_element] = $form_element_properties;


      }
    }
  }

    //'#default_value' => list_allowed_values_string(empty($settings[$subfield]['select']['allowed_values']) ? array() : $settings[$subfield]['select']['allowed_values']),

  return $form;
}



/**
 * AJAX callback.
 *
 * @internal
 *   Form: hook_field_widget_settings_form().
 *   Form element: number_of_fields.
 */
function _composed_field_number_of_fields_ajax_callback($form, $form_state) {
    
}

/**
 * AJAX callback.
 *
 * @internal
 *   Form: hook_field_widget_settings_form().
 *   Form element: _#type.
 */
function _composed_field_type_ajax_callback($form, $form_state) {
    
}

/**
 * AJAX callback.
 *
 * @internal
 *   Form: hook_field_widget_settings_form().
 *   Form element: enabled.
 */
function _composed_field_enabled_ajax_callback($form, $form_state) {
    
}

/**
 * Implements hook_field_widget_form().
 */
function composed_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  
  
  
  
  return $element;  
}


/**
 * Form Control Attributes.
 *
 * @see http://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7
 *
 * @return Array
 *   Map of the form controls api.
 */
function _composed_field_form_controls_api() {

  $description_options = '<p>' . t('The possible values this field can contain. Enter one value per line, in the format key|label.');
  $description_options .= '<br/>' . t('The key is the stored value. The label will be used in displayed values and edit forms.');
  $description_options .= '<br/>' . t('The label is optional: if a line contains a single string, it will be used as key and label.');
  $description_options .= '</p>';

  $form_controls = array(
    '#type'  => array(
      'widget_form' => array(
        'value' => array(
          '#type' => 'select',
          '#options' => array(
            'checkbox' => t('Checkbox'),
            'checkboxes' => t('Checkboxes'),
            'date' => t('Date'),
            'fieldset' => t('Fieldset'),
            'file' => t('File'),
            'machine_name' => t('Machine name'),
            'managed_file' => t('Managed file'),
            'password' => t('Password'),
            'password_confirm' => t('Password confirm'),
            'radio' => t('Radio'),
            'radios' => t('Radios'),
            'select' => t('Select'),
            'tableselect' => t('Table select'),
            'text_format' => t('Text format'),
            'textarea' => t('Text area'),
            'textfield' => t('Text field'),
            'vertical_tabs' => t('Vertical tabs'),
            'weight' => t('Weight'),
          ),
          '#required' => TRUE,
          '#ajax' => array(
            'callback' => '_composed_field_type_ajax_callback',
          ),
        ),
      ),
      'supported_types' => NULL,
    ),
    '#title' => array(
      'widget_form' => array(
        'value' => array(
          '#type' => 'textfield',
        ),
      ),
      'supported_types' => array(
        'checkbox',
        'checkboxes',
        'date',
        'fieldset',
        'file',
        'machine_name',
        'managed_file',
        'password',
        'password_confirm',
        'radio',
        'radios',
        'select',
        'text_format',
        'textarea',
        'textfield',
        'weight',
      ),
    ),
    '#description' => array(
      'widget_form' => array(
        'value' => array(
          '#type' => 'textfield',
        ),
      ),
      'supported_types' => array(
        'checkbox',
        'checkboxes',
        'date',
        'fieldset',
        'file',
        'machine_name',
        'managed_file',
        'password',
        'password_confirm',
        'radio',
        'radios',
        'select',
        'text_format',
        'textarea',
        'textfield',
        'weight',
      ),
    ),
    '#options' => array(
      'widget_form' => array(
          'value' => array(
          '#type' => 'textarea',
          '#title' => t('Allowed values list for '),
          //'#type' => 'text_format',
          //'#format' => 'php_code',
          //'#description' => 'test',
          '#description' => $description_options,
        ),
      ),
      'supported_types' => array('checkboxes','radios','select','tableselect'),
    ),
    /*'#default_value' => array(
      'widget_form' => array(
        '#type' => 'textfield',
      ),
      'supported_types' => array(
        'checkbox',
        'checkboxes',
        'date',
        'machine_name',
        'radio',
        'radios',
        'select',
        'tableselect',
        'text_format',
        'textarea',
        'textfield',
        'weight',
      ),
    ),*/
    '#prefix' => array(
      'widget_form' => array(
        'value' => array(
          '#type' => 'textfield',
        ),
      ),
      'supported_types' => array(
        'checkbox',
        'checkboxes',
        'date',
        'fieldset',
        'file',
        'machine_name',
        'managed_file',
        'password',
        'password_confirm',
        'radio',
        'radios',
        'select',
        'tableselect',
        'text_format',
        'textarea',
        'textfield',
        'vertical_tabs',
        'weight',
      ),
    ),
    '#suffix' => array(
      'widget_form' => array(
        'value' => array(
          '#type' => 'textfield',
        ),
      ),
      'supported_types' => array(
        'checkbox',
        'checkboxes',
        'date',
        'fieldset',
        'file',
        'machine_name',
        'managed_file',
        'password',
        'password_confirm',
        'radio',
        'radios',
        'select',
        'tableselect',
        'text_format',
        'textarea',
        'textfield',
        'vertical_tabs',
        'weight',
      ),
    ),
    '#required' => array(
      'widget_form' => array(
        'value' => array(
          '#type' => 'checkbox',
          '#field_suffix' => '<b>' . t('Make it required') . '</b>',
          '#title' => t('Required '),
          '#title_display' => 'before',
        ),
      ),
      'supported_types' => array(
        'checkbox',
        'checkboxes',
        'date',
        'file',
        'machine_name',
        'password',
        'password_confirm',
        'radio',
        'radios',
        'select',
        'text_format',
        'textarea',
        'textfield',
        'weight',
      ),
    ),
    '#size' => array(
      'widget_form' => array(
        'value' => array(
          '#type' => 'textfield',
          '#element_validate' => array('element_validate_number'),
        ),
      ),
      'supported_types' => array(
        'file',
        'machine_name',
        'password',
        'password_confirm',
        'select',
        'textfield',
      ),
    ),
    '#maxlength' => array(
      'widget_form' => array(
        'value' => array(
          '#type' => 'textfield',
          '#element_validate' => array('element_validate_number'),
        ),
      ),
      'supported_types' => array('machine_name','textfield'),
    ),
    
    /*
    '#access' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#after_build' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#array_parents' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#attached' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#element_validate' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#parents' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#post_render' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#pre_render' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#process' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#states' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#theme' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#theme_wrappers' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#tree' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#value_callback' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#weight' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'vertical_tabs',
      'weight',
    ),
    '#title_display' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'text_format',
      'textarea',
      'textfield',
      'weight',
    ),
    '#attributes' => array(
      'checkbox',
      'checkboxes',
      'date',
      'fieldset',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
      'weight',
    ),
    '#disabled' => array(
      'checkbox',
      'checkboxes',
      'date',
      'file',
      'machine_name',
      'managed_file',
      'password',
      'password_confirm',
      'radio',
      'radios',
      'select',
      'text_format',
      'textarea',
      'textfield',
      'weight',
    ),
    '#ajax' => array(
      'checkbox',
      'checkboxes',
      'machine_name',
      'radio',
      'radios',
      'select',
      'tableselect',
      'text_format',
      'textarea',
      'textfield',
    ),
    '#field_prefix' => array(
      'checkbox',
      'machine_name',
      'password',
      'password_confirm',
      'radio',
      'select',
      'textarea',
      'textfield',
    ),
    '#field_suffix' => array(
      'checkbox',
      'machine_name',
      'password',
      'password_confirm',
      'radio',
      'select',
      'textarea',
      'textfield',
    ),
    '#return_value' => array('checkbox','radio'),
    '#multiple' => array('select','tableselect'),
    '#cols' => array('text_format','textarea'),
    '#resizable' => array('text_format','textarea'),
    '#rows' => array('text_format','textarea'),
    '#autocomplete_path' => array('machine_name','textfield'),
    '#collapsed' => array('fieldset'),
    '#collapsible' => array('fieldset'),
    '#group' => array('fieldset'),
    '#empty_option' => array('select'),
    '#empty_value' => array('select'),
    '#empty' => array('tableselect'),
    '#header' => array('tableselect'),
    '#js_select' => array('tableselect'),
    '#default_tab' => array('vertical_tabs'),
    '#delta' => array('weight'),*/
  );

  return $form_controls;
}

